name = "cheapraidbanners"
compatibility_date = "2025-10-25"
main = "src/index.js"

account_id = "5e7fb995b74586d322a72a99770b31dc"

routes = ["cheapraidbanners.com/stats*"]  

[triggers]

crons = ["*/1 * * * *"]

# KV namespace binding: replace id with the namespace id you create (see next steps)
[[kv_namespaces]]
binding = "BUNGIE_STATS"
id = "b7b45a67f08a49da9157cfcd57cda5b0"

workers_dev = false
