name = "cheapraidbanners"
compatibility_date = "2025-10-25"
main = "src/index.js"

account_id = "5e7fb995b74586d322a72a99770b31dc"

# Cron schedule
[triggers]
crons = ["*/5 * * * *"]

# KV namespace binding (replace with the actual namespace id from `npx wrangler kv namespace list`)
[[kv_namespaces]]
binding = "BUNGIE_STATS"
id = "b7b45a67f08a49da9157cfcd57cda5b0"

# Durable Objects binding
[durable_objects]
  [[durable_objects.bindings]]
  name = "GLOBAL_STATS"
  class_name = "GlobalStats"

# For Free-plan accounts, use new_sqlite_classes to create the SQLite-backed DO namespace.
# Use a unique migration tag that hasn't been applied before (here: add-globalstats-20251025).
[[migrations]]
tag = "add-globalstats-20251025"
new_sqlite_classes = ["GlobalStats"]

# top-level flag — must be at top-level (not inside any table)
workers_dev = false