name = "cheapraidbanners"
compatibility_date = "2025-10-25"
main = "src/index.js"

account_id = "5e7fb995b74586d322a72a99770b31dc"

routes = [
  "cheapraidbanners.com/stats*",
  "cheapraidbanners.com/run-update*",
  "cheapraidbanners.com/admin/refresh*",
  "cheapraidbanners.com/members*"
]

[triggers]
crons = [
  "*/5 8-21 * * *",   # every 5 minutes during day -> clears run often
  "*/30 22-7 * * *"   # every 30 minutes overnight -> clears run less often
]

[[kv_namespaces]]
binding = "BUNGIE_STATS"
id = "369e27f8c9514999aa11d1dd5aacbb19"

[durable_objects]
bindings = [
  { name = "GLOBAL_STATS", class_name = "GlobalStats" }
]

[[migrations]]
tag = "add-globalstats-20251025-01"

workers_dev = false

[vars]
BUNGIE_CLAN_ID = "5335552"
BUNGIE_CLAN_ROSTER_ENDPOINT = "https://www.bungie.net/Platform/GroupV2/{clanId}/Members/"
BUNGIE_MEMBER_STATS_ENDPOINT_TEMPLATE = "https://www.bungie.net/platform/Player/{membershipType}/{membershipId}/Profile/"

BUNGIE_FETCH_CONCURRENCY = "10"
BUNGIE_PER_REQUEST_TIMEOUT_MS = "7000"

MIN_MEMBERS_UPDATE_INTERVAL_MS = "10800000" # 3 hours for members
MIN_CLEARS_UPDATE_INTERVAL_MS  = "300000"   # 5 minutes for clears