name = "cheapraidbanners"
compatibility_date = "2025-10-25"
main = "src/index.js"

account_id = "5e7fb995b74586d322a72a99770b31dc"

routes = [
  "cheapraidbanners.com/stats*",
  "cheapraidbanners.com/run-update*",
  "cheapraidbanners.com/admin/refresh*",
  "cheapraidbanners.com/members*"
]

[triggers]
# Cron every 5 minutes (keeps member list fresh and runs conditional dispatch)
crons = ["*/5 * * * *"]

[[kv_namespaces]]
binding = "BUNGIE_STATS"
id = "3ac5034307be43da8c41bba24cb67c87"

[durable_objects]
bindings = [
  { name = "GLOBAL_STATS", class_name = "GlobalStats" },
  { name = "MEMBER_WORKER", class_name = "MemberWorker" }
]

[vars]
BUNGIE_CLAN_ID = "5335552"
BUNGIE_CLAN_ROSTER_ENDPOINT = "https://www.bungie.net/Platform/GroupV2/{clanId}/Members/"
BUNGIE_MEMBER_STATS_ENDPOINT_TEMPLATE = "https://www.bungie.net/platform/Player/{membershipType}/{membershipId}/Profile/"

# runtime tuning
BUNGIE_FETCH_CONCURRENCY = "1"
BUNGIE_PER_REQUEST_TIMEOUT_MS = "15000"
BUNGIE_FETCH_RETRIES = "3"
BUNGIE_FETCH_BACKOFF_MS = "500"
BUNGIE_ACTIVITY_MAX_PAGES = "2000"

# dispatch / KV tuning
MEMBER_DISPATCH_THROTTLE_MS = "100"
KV_PER_MEMBER_BATCH_SIZE = "50"

# online/offline intervals (ms)
ONLINE_CLEARS_INTERVAL_MS = "300000"   # 5 minutes
OFFLINE_CLEARS_INTERVAL_MS = "7200000" # 2 hours
