name = "cheapraidbanners"
compatibility_date = "2025-10-25"
main = "src/index.js"

account_id = "5e7fb995b74586d322a72a99770b31dc"

# Cron schedule: run every 5 minutes
[triggers]
crons = ["*/1 * * * *"]

# KV namespace binding - fill this ID after running kv namespace create or listing existing
[[kv_namespaces]]
binding = "BUNGIE_STATS"
id = "0c93637a616346cdbc322b565f101124"

# Durable Objects binding
[durable_objects]
  [[durable_objects.bindings]]
  name = "GLOBAL_STATS"
  class_name = "GlobalStats"

# For Free plan: use new_sqlite_classes. Use a unique tag each time you create classes.
[[migrations]]
tag = "add-globalstats-20251025-unique"
new_sqlite_classes = ["GlobalStats"]

# top-level flag
workers_dev = false