name = "cheapraidbanners"
compatibility_date = "2025-10-25"
main = "src/index.js"

# Replace with your account id
account_id = "5e7fb995b74586d322a72a99770b31dc"

# Register only the API routes the Worker should handle (Pages will handle the rest)
routes = ["cheapraidbanners.com/stats*", "cheapraidbanners.com/run-update*"]


[triggers]
crons = [
  "*/5 8-21 * * *",   # every 5 minutes between 08:00 and 21:59 UTC (day)
  "*/15 22-23 * * *", # every 30 minutes between 22:00 and 23:59 UTC (night)
  "*/30 0-7 * * *"    # every 30 minutes between 00:00 and 07:59 UTC (night)
]

# KV namespace binding - replace with the namespace id returned from `wrangler kv namespace create` or `kv namespace list`
[[kv_namespaces]]
binding = "BUNGIE_STATS"
id = "0c93637a616346cdbc322b565f101124"

# Durable Objects
[durable_objects]
  [[durable_objects.bindings]]
  name = "GLOBAL_STATS"
  class_name = "GlobalStats"

# Free-plan Durable Objects need this migration form (use a unique tag)
[[migrations]]
tag = "add-globalstats-20251025-01"


# Top-level flag
workers_dev = false