name = "cheapraidbanners"
compatibility_date = "2025-10-25"
main = "src/index.js"

account_id = "5e7fb995b74586d322a72a99770b31dc"


[durable_objects]
bindings = [
  { name = "VISITOR_COUNTER", class_name = "VisitorCounter" }
]

# Durable Object migrations ensure Wrangler wires the DO class to the binding.
[[migrations]]
tag = "v1"
new_sqlite_classes = ["VisitorCounter"]